from pydantic import BaseModel, Field
from typing import List

class RFIItem(BaseModel):
    """
    Structured output for an RFI (Request for Information) generated by the AI.
    """
    title: str = Field(..., description="Short, descriptive title for the RFI")
    question: str = Field(..., description="The exact question drafted for the architect/owner")
    impacted_trades: List[str] = Field(..., description="Trades affected by this gap")
    source_sheet_or_spec: str = Field(..., description="Must explicitly name the drawing or spec section causing confusion")
    confidence_level: str = Field(..., description="'High', 'Medium', or 'Low' confidence in this gap")

class RFIListResponse(BaseModel):
    rfis: List[RFIItem]
    total_count: int
